stages:
  - name: madgraph
    dependencies: ["init"]
    scheduler:
      scheduler_type: "singlestep-stage"
      parameters:
        outputlhe: "{workdir}/events.lhe"
        n_events: { step: init, output: n_events }
        proc_card: { step: init, output: proc_card }
        param_card: { step: init, output: param_card }
        ufotar: { step: init, output: ufotar }
      step: { $ref: "madgraph.yml" }
